services:
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      API_URL: "http://backend"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: ./server
    command: npm run dev-with-migration
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DATABASE_URL: "mysql://root:1234pass@db/todos"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'todos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234pass'

volumes:
  db-data:
