services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'todos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234pass'

volumes:
  db-data:
